const fixtureTypes = [
  {
    id: 'generic',
    name: 'Generic',
    mapping: ['m'],
    shape: 'circle',
    border: 'dashed',
  },
  {
    id: 'white3ch',
    name: 'White 3ch',
    mapping: ['m', 'str', 'cur'],
    shape: 'circle',
    border: 'dashed',
  },
  {
    id: 'cwww',
    name: 'Cold/warm 5ch',
    mapping: ['w', 'ww', 'm', 'str', 'ct'],
    shape: 'circle',
    border: 'dashed',
    xSize: 8,
    ySize: 8,
  },
  {
    id: 'rgb',
    name: 'RGB',
    mapping: ['r', 'g', 'b'],
    shape: 'circle',
    xSize: 4,
    ySize: 4,
    border: 'solid',
  },
  {
    id: 'rgb5ch',
    name: 'RGB PAR56 5ch',
    mapping: ['r', 'g', 'b', 'm', 'str'],
    shape: 'circle',
    border: 'solid',
  },
  {
    id: '8x30w5',
    name: 'RGB 8x30W 5ch',
    mapping: ['r', 'g', 'b', 'm', 'str'],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 6,
  },
  {
    id: '8x30w28',
    name: 'RGB 8x30W 28ch',
    mapping: [
      'eff',
      'm',
      'str',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'wb',
    ],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 6,
  },
  {
    id: 'rgbw15',
    name: 'RGBW 15ch',
    mapping: [
      'macro',
      'm',
      'str',
      'r',
      'g',
      'b',
      'w',
      'r',
      'g',
      'b',
      'w',
      'r',
      'g',
      'b',
      'w',
    ],
    shape: 'square',
    border: 'solid',
    xSize: 8,
  },
  {
    id: 'rgbwauv',
    name: 'RGBWAUV',
    mapping: ['r', 'g', 'b', 'w', 'a', 'uv'],
  },
  {
    id: 'bar5',
    name: 'Bar 4x30W RGB 5ch',
    mapping: ['r', 'g', 'b', 'm', 'str'],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 3,
  },
  {
    id: 'bar15',
    name: 'Bar 4x30W RGB 15ch',
    mapping: [
      'eff',
      'm',
      'str',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
      'r',
      'g',
      'b',
    ],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 3,
  },
  {
    id: 'flach',
    name: 'Flat RGB',
    mapping: ['m', 'r', 'g', 'b', 'fn', 'str'],
    shape: 'square',
    border: 'solid',
  },
  {
    id: 'flach2',
    name: 'Flat RGBW',
    mapping: ['r', 'g', 'b', 'w', 'm', 'str'],
    shape: 'square',
    border: 'solid',
    ySize: 7,
  },
  {
    id: 'waterproof7',
    name: 'Waterproof 7ch',
    mapping: ['m', 'r', 'g', 'b', 'a', 'w', 'uv'],
    shape: 'square',
    xSize: 6,
    ySize: 4,
    border: 'solid',
  },
  {
    id: 'waterproof9',
    name: 'Waterproof 9ch',
    mapping: ['m', 'r', 'g', 'b', 'a', 'w', 'uv', 'str', 'cur'],
    shape: 'square',
    xSize: 6,
    ySize: 4,
  },
  {
    id: 'blinder6',
    name: 'Blinder 6ch',
    mapping: ['r', 'g', 'b', 'w', 'm', 'str'],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 10,
  },
  {
    id: 'blinder19',
    name: 'Blinder 19ch',
    mapping: [
      'eff',
      'm',
      'fla',
      'r',
      'g',
      'b',
      'w',
      'r',
      'g',
      'b',
      'w',
      'r',
      'g',
      'b',
      'w',
      'r',
      'g',
      'b',
      'w',
    ],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 10,
  },
  {
    id: 'hazer',
    name: 'Hazer',
    mapping: ['m', 'fan'],
    shape: 'square',
    border: 'solid',
    xSize: 10,
    ySize: 7,
  },
  {
    id: 'uv',
    name: 'UV',
    mapping: ['m', 'str', 'uv', 'int'],
    shape: 'square',
    border: 'dashed',
    xSize: 10,
  },
  {
    id: 'washerx1936',
    name: 'Washer X19 36ch',
    mapping: [
      'pan',
      'panf',
      'tilt',
      'tiltf',
      'pts',
      'str',
      'm',
      'ms',
      'z',
      'r',
      'g',
      'b',
      'w',
      'l',
      'uv',
      'a',
      'r',
      'g',
      'b',
      'w',
      'l',
      'uv',
      'a',
      'r',
      'g',
      'b',
      'w',
      'l',
      'uv',
      'a',
      'cp',
      'prg',
      'mak',
      'ps',
      'pf',
      'rst',
    ],
    shape: 'circle',
    border: 'dotted',
    xSize: 10,
    ySize: 10,
  },
  {
    id: 'washerrgb15',
    name: 'Washer RGBW 15ch',
    mapping: [
      'pan',
      'panf',
      'tilt',
      'tiltf',
      'mvspeed',
      'str',
      'm',
      'mspeed',
      'zoom',
      'r',
      'g',
      'b',
      'w',
      'col',
      'reset',
    ],
    shape: 'circle',
    border: 'dotted',
    xSize: 7,
    ySize: 7,
  },
  {
    id: 'movingspot',
    name: 'Moving Spot',
    mapping: [
      'pan',
      'panf',
      'tilt',
      'tiltf',
      'mvspeed',
      'funpantilt',
      'funshutter',
      'shutter',
      'm',
      'funcol',
      'col',
      'goboshake',
      'gobo',
      'prism',
      'prismrot',
      'reset',
    ],
    shape: 'circle',
    border: 'dotted',
    xSize: 9,
    ySize: 9,
  },
]

module.exports = fixtureTypes
